### ISSUE TITLE
Electrum Personal Server instead of Electrumx in the readme

### ISSUE THREAD

**Issue by manbyt** [Furunodo/sovereignbox#2]
Here: 
done
full node ansible script

bitcoind
electrumx
and here:
electrumx for https://github.com/chris-belcher/electrum-personal-server

**Comment by Furunodo** [comment]
Moved back to ElectrumX as personal-server [doesn't fit](https://github.com/chris-belcher/electrum-personal-server#how-is-this-different-from-other-electrum-servers-) the requirements: we want to set up a full node server that serve many different wallets out there without any of the configuration based on a specific wallet (like xpub).
